# Generated by Django 3.2.7 on 2021-12-18 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
